export const productActionTypes = {
  FETCH_PRODUCTS_DATA_START: 'FETCH_PRODUCTS_DATA_START',
  FETCH_PRODUCTS_DATA_SUCCESS: 'FETCH_PRODUCTS_DATA_SUCCESS',
  FETCH_PRODUCTS_DATA_FAILURE: 'FETCH_PRODUCTS_DATA_FAILURE',
};
